---
- name: add PostgreSQL repo key
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present

- name: install PostgreSQL and related packages
  yum: name={{ item }} state=latest
  with_items:
    - python-psycopg2
    - "postgresql{{ postgresql.version }}"
    - "postgresql{{ postgresql.version }}-devel"
    - "postgresql{{ postgresql.version }}-contrib"
    - "postgresql{{ postgresql.version }}-server"

- name: init PostgreSQL DB
  command: service postgresql-{{ postgresql.dot_version }} initdb

- name: ensure PostgreSQL is running
  service: name=postgresql-{{ postgresql.dot_version }} state=started enabled=true

- name: copy pg_hba config
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/{{ postgresql.dot_version }}/data/pg_hba.conf
  notify:
    - restart postgresql

- meta: flush_handlers

- name: create PostgreSQL user for laravel
  postgresql_user: name={{ postgresql.user_name }} password={{ postgresql.user_password }} role_attr_flags=CREATEDB,INHERIT
  sudo_user: postgres

- name: create postgresql database for application
  postgresql_db: name={{ postgresql.db_name }} owner={{ postgresql.user_name }} state=present
  sudo_user: postgres
