---
- name: create downloads folder
  file: state=directory path=/home/{{ user }}/downloads
  sudo: yes
  sudo_user: "{{ user }}"

- name: download zsh source
  get_url: url=http://sourceforge.net/projects/zsh/files/zsh/5.0.7/zsh-5.0.7.tar.gz/download dest=/home/{{ user }}/downloads
  sudo: yes
  sudo_user: "{{ user }}"

- name: extract zsh source
  unarchive: src=/home/{{ user }}/downloads/zsh-5.0.7.tar.gz dest=/home/{{ user }}/downloads/ copy=no
  sudo: yes
  sudo_user: "{{ user }}"

- name: install zsh from source
  shell: cd /home/{{ user }}/downloads/zsh-5.0.7/ && ./configure && make && make install

- name: add zsh to list of default shell
  lineinfile: dest=/etc/shells line="/usr/local/bin/zsh"

- name: set default shell for vargant user to zsh
  shell: chsh -s /usr/local/bin/zsh {{ user }}

- name: setup prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=/home/{{ user }}/.zprezto accept_hostkey=true
  sudo: yes
  sudo_user: "{{ user }}"

- name: get linux configuration file
  git: repo=https://github.com/linhmtran168/linux_dotfiles.git dest=/home/{{ user }}/dotfiles accept_hostkey=true
  sudo: yes
  sudo_user: "{{ user }}"

- name: link zsh, tmux configurations
  file: state=link src=/home/{{ user }}/dotfiles/{{ item }} path=/home/{{ user }}/{{ item }}
  with_items:
    - .tmux.conf
    - .zshrc
    - .zprofile
    - .zpreztorc
  sudo: yes
  sudo_user: "{{ user }}"

- name: remove default starting tmux when login
  lineinfile: dest=/home/{{ user }}/dotfiles/.zpreztorc regexp="(tmux).*(remote)" state=absent

# - name: link zpreztorc theme
#   file: state=link src=/home/{{ user }}/dotfiles/{{ item}} path=/home/{{ user }}/.zprezto/modules/prompt/functions/{{ item }}
#   with_items:
#     - prompt_superlinh_setup
#   sudo: yes
#   sudo_user: "{{ user }}"
